version: '3.8'
services:
  portfolio: 
    container_name: portfolio
    restart: unless-stopped
    build:
      context: .
      args:
        REACT_APP_TELEGRAM_BOT_TOKEN: ""
        REACT_APP_TELEGRAM_CHAT_ID: ""
    ports:
      - '3000:3000'